import { defaultState } from "./defaults";
import type { WizardState } from "./types";

export type PersonaGroup = "common" | "extra" | "dont";

export type Persona = {
  id: string;
  title: string;
  summary: string;
  formName: string;
  group: PersonaGroup;
  state: WizardState;
};

export const PERSONA_SECTIONS: { group: PersonaGroup; title: string; text: string }[] = [
  {
    group: "common",
    title: "Vanliga fall",
    text: "Det skolan ser oftast. Fingerade familjer.",
  },
  {
    group: "extra",
    title: "Andra kategorier och blanketter",
    text: "D, E och F samt kultur, samhälle och synnerliga skäl.",
  },
  {
    group: "dont",
    title: "Så här gör ni inte",
    text: "Två vanliga fallgropar. Appen stoppar här — byt spår.",
  },
];

function base(partial: Partial<WizardState>): WizardState {
  return {
    ...defaultState(),
    understoodSchoolSubmits: true,
    consentProcessing: true,
    whyApproved: true,
    letterApproved: true,
    aiConsent: true,
    writeMyself: false,
    currentStepId: "pack",
    stayPlace: "Spanien, Mallorca",
    livesWithAbroadGuardian: "yes",
    hasSecondGuardian: true,
    ...partial,
  };
}

export const PERSONAS: Persona[] = [
  {
    id: "vd-ab",
    title: "VD i svenskt AB",
    summary: "Äger bolaget. Extern revisor skriver under del 2. Vanligast på Mallorca.",
    formName: "Intyg om tjänstgöring, kategori C",
    group: "common",
    state: base({
      studentFirstName: "Elsa",
      studentLastName: "Holm",
      studentDateOfBirth: "2010-03-14",
      year: "1",
      program: "ekonomi",
      guardian1: {
        firstName: "Erik",
        lastName: "Holm",
        dateOfBirth: "1978-06-02",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Anna",
        lastName: "Holm",
        dateOfBirth: "1980-11-19",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2024-08",
      stayType: "indefinite",
      reason: "employment",
      employerForm: "swedish_ab",
      isOwnerOrCeo: "yes",
      category: "C",
      employerName: "Holm Advisory AB (exempel)",
      employerOrgNr: "559000-0101",
      employerAddress: "Carrer de la Unió 12, Palma",
      employerCountry: "Spanien",
      jobTitle: "VD",
      employmentType: "permanent",
      workAbroadFrom: "2024-08",
      jobPoints:
        "1. Driver kunduppdrag mot hotell och fastighetsbolag på Mallorca\n2. Förhandlar och följer upp avtal på plats\n3. Ansvarar för den lokala verksamheten",
      whyRaw:
        "Erik är VD i Holm Advisory AB. Bolaget har löpande uppdrag mot hotell och fastighetsägare på Mallorca. Han behöver vara på plats för möten, avtalsgenomgångar och uppföljning. Det är uppdraget som gör att familjen bor här, inte tvärtom.",
      whyGenerated:
        "Vårdnadshavaren är VD i Holm Advisory AB. Arbetet består i att driva kunduppdrag mot hotell och fastighetsbolag på Mallorca: förhandla avtal, träffa motparter och följa upp leverans på plats. Det kräver närvaro i Palma. Familjen bor här därför att tjänsten gör det, inte av privata skäl. Utlandsvistelsen följer av tjänsten.",
      canIndependentSign: "no",
      signerType: "auditor",
      auditorName: "Mikael Sund, Sund Revision AB",
      auditorEmail: "mikael@exempel.se",
      letterGenerated: "",
      dailyLanguage: "swedish",
      studentSwedish: "follows",
    }),
  },
  {
    id: "anstalld-ab",
    title: "Anställd i svenskt bolag",
    summary: "Utsänd av arbetsgivaren. HR eller chef skriver under.",
    formName: "Intyg om tjänstgöring, kategori C",
    group: "common",
    state: base({
      studentFirstName: "Noah",
      studentLastName: "Berg",
      studentDateOfBirth: "2009-09-01",
      year: "2",
      program: "samhalle",
      guardian1: {
        firstName: "Lisa",
        lastName: "Berg",
        dateOfBirth: "1982-04-21",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Pablo",
        lastName: "Berg",
        dateOfBirth: "1979-12-08",
        citizenship: "not_swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2025-01",
      stayType: "limited",
      stayTo: "2027-12",
      reason: "employment",
      employerForm: "swedish_ab",
      isOwnerOrCeo: "no",
      category: "C",
      employerName: "Nordhavn Export AB (exempel)",
      employerOrgNr: "556000-0202",
      employerAddress: "Kungsgatan 8, Stockholm",
      employerCountry: "Sverige",
      employerWebsite: "https://exempel.se",
      jobTitle: "Marknadschef Sydeuropa",
      employmentType: "permanent",
      workAbroadFrom: "2025-01",
      workAbroadTo: "2027-12",
      jobPoints:
        "1. Ansvarar för kunder i Spanien och Portugal\n2. Är på plats hos återförsäljare och på mässor\n3. Bygger upp det lokala säljkontoret i Palma",
      whyRaw:
        "Lisa är anställd som marknadschef Sydeuropa. Bolaget har placerat henne i Palma för att hon ska kunna träffa återförsäljare, vara på mässor och bygga kontoret. Hon kan inte göra det från Stockholm.",
      whyGenerated:
        "Vårdnadshavaren är anställd som marknadschef Sydeuropa vid Nordhavn Export AB. Arbetet består i att ansvara för kunder i Spanien och Portugal, träffa återförsäljare och bygga upp det lokala säljkontoret i Palma. Bolaget har därför placerat henne där. Familjen bor här därför att tjänsten gör det, inte av privata skäl. Utlandsvistelsen följer av tjänsten.",
      canIndependentSign: "yes",
      signerName: "Karin Ek",
      signerTitle: "HR-chef",
      signerEmail: "karin.ek@exempel.se",
      signerPhone: "+46 8 000 00 00",
      signerType: "hr",
      letterGenerated: "",
      dailyLanguage: "mixed",
      studentSwedish: "follows",
    }),
  },
  {
    id: "myndighet",
    title: "Svensk myndighet",
    summary: "Tjänstgöring vid svensk myndighet. Chef skriver under.",
    formName: "Intyg om tjänstgöring, kategori A",
    group: "common",
    state: base({
      studentFirstName: "Vera",
      studentLastName: "Lind",
      studentDateOfBirth: "2011-01-22",
      year: "1",
      program: "samhalle",
      guardian1: {
        firstName: "Johan",
        lastName: "Lind",
        dateOfBirth: "1976-08-30",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Maja",
        lastName: "Lind",
        dateOfBirth: "1977-02-14",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2023-09",
      stayType: "limited",
      stayTo: "2026-08",
      reason: "employment",
      employerForm: "swedish_authority",
      isOwnerOrCeo: "no",
      category: "A",
      employerName: "Exempelmyndigheten",
      employerOrgNr: "202100-0000",
      employerAddress: "Regeringsgatan 1, Stockholm",
      employerCountry: "Sverige",
      jobTitle: "Handläggare, utlandsplacering",
      employmentType: "temporary",
      workAbroadFrom: "2023-09",
      workAbroadTo: "2026-08",
      jobPoints:
        "1. Följer upp samarbeten med spanska motparter\n2. Deltar i möten på plats i Palma och Madrid\n3. Rapporterar hem till myndigheten",
      whyRaw:
        "Johan är utsänd av myndigheten för en tidsbegränsad placering. Arbetet är att följa upp samarbeten och sitta i möten med spanska motparter. Placeringen är beslutad av arbetsgivaren.",
      whyGenerated:
        "Vårdnadshavaren tjänstgör vid Exempelmyndigheten som handläggare med utlandsplacering. Arbetet består i att följa upp samarbeten med spanska motparter, delta i möten i Palma och Madrid och rapportera hem. Myndigheten har tidsbegränsat placerat honom utomlands. Familjen bor här därför att placeringen kräver det. Vistelsen följer av tjänsten.",
      canIndependentSign: "yes",
      signerName: "Eva Norén",
      signerTitle: "Enhetschef",
      signerEmail: "eva.noren@exempel.se",
      signerPhone: "+46 8 111 11 11",
      signerType: "hr",
      letterGenerated: "",
    }),
  },
  {
    id: "studier",
    title: "Studier på plats",
    summary: "Vårdnadshavaren läser på universitet i Palma med studiemedel.",
    formName: "Blankett studier och forskning",
    group: "common",
    state: base({
      studentFirstName: "Leo",
      studentLastName: "Soto",
      studentDateOfBirth: "2010-07-05",
      year: "1",
      program: "ekonomi",
      guardian1: {
        firstName: "Maria",
        lastName: "Soto",
        dateOfBirth: "1984-05-17",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Diego",
        lastName: "Soto",
        dateOfBirth: "1983-03-09",
        citizenship: "not_swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2025-09",
      stayType: "limited",
      stayTo: "2027-06",
      reason: "studies",
      institutionName: "Universitat de les Illes Balears (exempel)",
      institutionCountry: "Spanien",
      studyDescription: "Masterprogram i turismekonomi, undervisning på plats i Palma.",
      studyMode: "onsite",
      funding: "csn",
      fundingPayer: "CSN",
      fundingPeriod: "2025-09 – 2027-06",
      whyRaw:
        "Maria läser en master på UIB i Palma. Kurserna och seminarierna är på campus. Hon har studiemedel från CSN. Det är studierna som gör att hon måste vara här.",
      whyGenerated:
        "Vårdnadshavaren studerar en master i turismekonomi vid Universitat de les Illes Balears. Undervisningen sker på plats i Palma. Studierna finansieras med studiemedel från CSN. Vistelsen krävs för att studierna ska kunna genomföras på campus, inte på distans från Sverige. Det är studierna som styr var familjen bor.",
    }),
  },
  {
    id: "internationell",
    title: "Internationell organisation",
    summary: "Tjänst vid internationell organisation. HR skriver under.",
    formName: "Intyg om tjänstgöring, kategori B",
    group: "common",
    state: base({
      studentFirstName: "Alma",
      studentLastName: "Nyström",
      studentDateOfBirth: "2008-12-11",
      year: "3",
      program: "samhalle",
      guardian1: {
        firstName: "Karl",
        lastName: "Nyström",
        dateOfBirth: "1975-10-03",
        citizenship: "swedish_plus",
      },
      guardian2: {
        firstName: "Sofia",
        lastName: "Nyström",
        dateOfBirth: "1976-01-28",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2022-03",
      stayType: "indefinite",
      reason: "employment",
      employerForm: "international_org",
      isOwnerOrCeo: "no",
      category: "B",
      employerName: "Exempel-organisationen för regionalt samarbete",
      employerOrgNr: "IO-0001",
      employerAddress: "Passeig Mallorca 4, Palma",
      employerCountry: "Spanien",
      jobTitle: "Projektledare",
      employmentType: "permanent",
      workAbroadFrom: "2022-03",
      jobPoints:
        "1. Leder ett samarbetsprojekt med kontor i Palma\n2. Håller arbetsmöten med partnerländer på plats\n3. Kan inte skötas från Sverige",
      whyRaw:
        "Karl är projektledare vid en internationell organisation med kontor i Palma. Projektet sitter här. Han måste vara på plats för möten och samordning.",
      whyGenerated:
        "Vårdnadshavaren är projektledare vid Exempel-organisationen för regionalt samarbete. Arbetet består i att leda ett samarbetsprojekt med kontor i Palma och hålla arbetsmöten med partnerländer på plats. Tjänsten är förlagd hit. Familjen bor här därför att uppdraget sitter här, inte av privata skäl. Vistelsen följer av tjänstgöringen.",
      canIndependentSign: "yes",
      signerName: "Ines Martí",
      signerTitle: "Head of HR",
      signerEmail: "ines@exempel.org",
      signerType: "hr",
      letterGenerated: "",
      dailyLanguage: "swedish",
      studentSwedish: "follows",
    }),
  },
  {
    id: "kategori-d",
    title: "Utländskt bolag, svenskt ägande",
    summary: "Spanskt bolag där ett svenskt AB har bestämmande inflytande. Kategori D.",
    formName: "Intyg om tjänstgöring, kategori D",
    group: "extra",
    state: base({
      studentFirstName: "Iris",
      studentLastName: "Falk",
      studentDateOfBirth: "2010-05-03",
      year: "1",
      program: "ekonomi",
      guardian1: {
        firstName: "Tomas",
        lastName: "Falk",
        dateOfBirth: "1977-09-12",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Ylva",
        lastName: "Falk",
        dateOfBirth: "1979-04-28",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2024-03",
      stayType: "indefinite",
      reason: "employment",
      employerForm: "foreign_company",
      isOwnerOrCeo: "no",
      category: "D",
      employerName: "Palma Retail SL (exempel)",
      employerOrgNr: "B-07000001",
      employerAddress: "Avinguda Jaume III 10, Palma",
      employerCountry: "Spanien",
      jobTitle: "Butikschef",
      swedishControllerName: "Falk Handel AB (exempel)",
      swedishControllerOrgNr: "556000-0303",
      ownershipPercent: "70",
      influenceDescription: "Det svenska bolaget utser styrelse och beslutar om budget och sortiment.",
      employmentType: "permanent",
      workAbroadFrom: "2024-03",
      jobPoints:
        "1. Driver den fysiska butiken i Palma\n2. Ansvarar för personal och leveranser på plats\n3. Rapporterar till det svenska moderbolaget",
      whyRaw:
        "Tomas är anställd i det spanska bolaget Palma Retail SL. Moderbolaget Falk Handel AB äger 70 procent och styr verksamheten. Arbetet är att driva butiken i Palma. Det kan inte göras från Sverige.",
      whyGenerated:
        "Vårdnadshavaren är anställd som butikschef vid Palma Retail SL. Det spanska bolaget kontrolleras av Falk Handel AB, som äger 70 procent och utser styrelse. Arbetet består i att driva den fysiska butiken i Palma, leda personal och ta emot leveranser. Tjänsten är förlagd till butiken. Familjen bor här därför att arbetet kräver närvaro, inte av privata skäl.",
      canIndependentSign: "yes",
      signerName: "Helena Falk",
      signerTitle: "CFO, Falk Handel AB",
      signerEmail: "helena@exempel.se",
      signerType: "hr",
      letterGenerated: "",
      dailyLanguage: "swedish",
      studentSwedish: "follows",
    }),
  },
  {
    id: "kategori-e",
    title: "Tillfällig tjänst, bolag med verksamhet i Sverige",
    summary: "Tidsbegränsad roll i utländskt bolag som också är aktivt i Sverige. Kategori E.",
    formName: "Intyg om tjänstgöring, kategori E",
    group: "extra",
    state: base({
      studentFirstName: "Melvin",
      studentLastName: "Åberg",
      studentDateOfBirth: "2009-11-18",
      year: "2",
      program: "samhalle",
      guardian1: {
        firstName: "Sara",
        lastName: "Åberg",
        dateOfBirth: "1981-02-07",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "David",
        lastName: "Åberg",
        dateOfBirth: "1978-08-16",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2025-03",
      stayType: "limited",
      stayTo: "2026-09",
      reason: "employment",
      employerForm: "foreign_company",
      isOwnerOrCeo: "no",
      category: "E",
      employerName: "Mediterranea Hotels SA (exempel)",
      employerOrgNr: "A-08000002",
      employerAddress: "Passeig Marítim 20, Palma",
      employerCountry: "Spanien",
      jobTitle: "Projektledare, nordisk försäljning",
      employmentType: "temporary",
      workAbroadFrom: "2025-03",
      workAbroadTo: "2026-09",
      jobPoints:
        "1. Samordnar kampanjer mot den svenska marknaden från hotellet i Palma\n2. Träffar leverantörer och kedjans svenska säljkontor\n3. Tjänsten är tidsbegränsad och kan inte skötas från Stockholm",
      whyRaw:
        "Sara är tillfälligt placerad hos Mediterranea Hotels SA. Bolaget har säljkontor i Sverige. Hon leder ett projekt mot den nordiska marknaden och måste sitta på hotellet i Palma under avtalsperioden.",
      whyGenerated:
        "Vårdnadshavaren är tidsbegränsat anställd som projektledare vid Mediterranea Hotels SA. Bolaget har verksamhet i Sverige via ett säljkontor. Arbetet består i att samordna kampanjer mot den nordiska marknaden och träffa leverantörer på plats i Palma. Placeringen har start- och slutdatum. Familjen bor här under avtalsperioden därför att projektet kräver närvaro.",
      canIndependentSign: "yes",
      signerName: "Jordi Serra",
      signerTitle: "HR Director",
      signerEmail: "jordi@exempel.es",
      signerType: "hr",
      letterGenerated: "",
      dailyLanguage: "mixed",
      studentSwedish: "follows",
    }),
  },
  {
    id: "kategori-f",
    title: "Tidsbegränsad tjänst vid utländsk juridisk person",
    summary: "Kategori F. Anställningsavtalet med start och slut måste lämnas till skolan.",
    formName: "Intyg om tjänstgöring, kategori F",
    group: "extra",
    state: base({
      studentFirstName: "Tuva",
      studentLastName: "Ek",
      studentDateOfBirth: "2011-06-09",
      year: "1",
      program: "ekonomi",
      guardian1: {
        firstName: "Henrik",
        lastName: "Ek",
        dateOfBirth: "1980-01-25",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Nora",
        lastName: "Ek",
        dateOfBirth: "1982-07-03",
        citizenship: "not_swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2025-09",
      stayType: "limited",
      stayTo: "2027-08",
      reason: "employment",
      employerForm: "foreign_company",
      isOwnerOrCeo: "no",
      category: "F",
      employerName: "Balearic Design Studio SL (exempel)",
      employerOrgNr: "B-07000003",
      employerAddress: "Carrer de Sant Feliu 4, Palma",
      employerCountry: "Spanien",
      jobTitle: "Art director",
      employmentType: "temporary",
      workAbroadFrom: "2025-09",
      workAbroadTo: "2027-08",
      jobPoints:
        "1. Leder formgivning för lokala uppdragsgivare\n2. Arbetet sker i studion i Palma\n3. Avtalet är tidsbegränsat i förväg",
      whyRaw:
        "Henrik har ett tidsbegränsat avtal med Balearic Design Studio SL. Avtalet anger start och slut. Arbetet är att leda formgivning i studion i Palma. Det kan inte göras på distans från Sverige.",
      whyGenerated:
        "Vårdnadshavaren är tidsbegränsat anställd som art director vid Balearic Design Studio SL. Avtalet anger start- och slutdatum i förväg. Arbetet består i att leda formgivning för lokala uppdragsgivare i studion i Palma. Tjänsten är förlagd dit. Familjen bor här under avtalsperioden därför att arbetet kräver närvaro. Anställningsavtalet lämnas till skolan.",
      canIndependentSign: "yes",
      signerName: "Marta Ribas",
      signerTitle: "Managing partner",
      signerEmail: "marta@exempel.es",
      signerType: "hr",
      letterGenerated: "",
      dailyLanguage: "swedish",
      studentSwedish: "follows",
    }),
  },
  {
    id: "kultur",
    title: "Kulturarbete",
    summary: "Huvudsaklig försörjning från kulturarbete på plats. Inte anställning i bolag.",
    formName: "Blankett kulturarbete",
    group: "extra",
    state: base({
      studentFirstName: "Signe",
      studentLastName: "Vall",
      studentDateOfBirth: "2010-02-21",
      year: "1",
      program: "samhalle",
      guardian1: {
        firstName: "Klara",
        lastName: "Vall",
        dateOfBirth: "1983-10-11",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Andreas",
        lastName: "Vall",
        dateOfBirth: "1981-05-06",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2024-09",
      stayType: "limited",
      stayTo: "2026-06",
      reason: "culture",
      cultureType: "Tonsättare och pianist",
      cultureWhere:
        "Skriver och repeterar för produktioner vid Teatre Principal och mindre scener i Palma. Arbetet kräver närvaro vid repetition och premiär.",
      cultureClients: "Teatre Principal, lokala ensembler (exempel)",
      culturePoints:
        "1. Komponerar och arrangerar på uppdrag\n2. Repeterar och medverkar på plats\n3. Cacheterna är den huvudsakliga inkomsten",
      cultureLivelihood: "main",
      cultureProof: "contract",
      whyRaw:
        "Klara försörjer sig på komposition och pianouppdrag i Palma. Kontrakten och repetitionerna är på plats. Det är inte ett sidoprojekt.",
      whyGenerated:
        "Vårdnadshavaren arbetar som tonsättare och pianist. Uppdragen är knutna till scener i Palma: komposition, repetition och medverkan vid föreställning. Kontrakten visar att cacheterna är den huvudsakliga försörjningen, inte ett komplement. Arbetet kan inte utföras från Sverige. Familjen bor här därför att uppdragen kräver närvaro. Bokslut eller kontrakt lämnas till skolan.",
    }),
  },
  {
    id: "samhalle",
    title: "Väsentligt för det svenska samhället",
    summary: "Hög tröskel. Kräver svensk aktör som kan styrka intresset på Sverige-nivå.",
    formName: "Blankett väsentligt för det svenska samhället",
    group: "extra",
    state: base({
      studentFirstName: "Otto",
      studentLastName: "Ryd",
      studentDateOfBirth: "2009-04-02",
      year: "2",
      program: "samhalle",
      guardian1: {
        firstName: "Linn",
        lastName: "Ryd",
        dateOfBirth: "1979-12-01",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Mats",
        lastName: "Ryd",
        dateOfBirth: "1977-03-22",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2023-08",
      stayType: "limited",
      stayTo: "2026-07",
      reason: "society",
      societyWhat:
        "Korrespondent för ett svenskt public service-bolag med bevakning av Spanien och Medelhavet (exempel).",
      societyWhySweden:
        "Bevakningen når svensk publik nationellt och är en del av det svenska medieuppdraget, inte ett lokalt sidouppdrag för familjen eller ett eget bolag.",
      societyVerifier: "Exempel: Sveriges Radio, utrikesredaktionen",
      whyRaw:
        "Linn är korrespondent. Uppdraget är att bevaka Spanien för svensk public service. Det är redaktionen i Sverige som styr uppdraget.",
      whyGenerated:
        "Vårdnadshavaren tjänstgör som korrespondent för ett svenskt public service-bolag med bevakning av Spanien. Uppdraget beslutas av redaktionen i Sverige och når svensk publik på nationell nivå. Vistelsen krävs för att bevakningen ska kunna göras på plats. Det är inte ett privat flyttskäl och inte ett eget bolags intresse. Intyg från den svenska uppdragsgivaren lämnas till skolan.",
    }),
  },
  {
    id: "synnerliga",
    title: "Synnerliga skäl",
    summary: "Undantag. Intyg lämnas i slutet kuvert — inga journaler i appen.",
    formName: "Blankett synnerliga skäl",
    group: "extra",
    state: base({
      studentFirstName: "Mira",
      studentLastName: "Dalén",
      studentDateOfBirth: "2011-08-30",
      year: "1",
      program: "ekonomi",
      guardian1: {
        firstName: "Sofie",
        lastName: "Dalén",
        dateOfBirth: "1985-06-14",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Jonas",
        lastName: "Dalén",
        dateOfBirth: "1984-01-19",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2025-01",
      stayType: "limited",
      stayTo: "2026-12",
      reason: "exceptional",
      exceptionalReasons:
        "Eleven behöver följa vårdnadshavaren under en dokumenterad vårdsituation. Inga detaljer i appen. Intyg från behandlande instans lämnas i slutet kuvert till skolan.",
      exceptionalWho: "student",
      exceptionalDocs: "exists",
      whyRaw:
        "Mira behöver vara med Sofie under en period som styrks med intyg. Vi lämnar intyget till skolan, inte här.",
      whyGenerated:
        "Eleven behöver följa vårdnadshavaren under en tidsbegränsad period som styrks av intyg från behandlande instans. Redogörelsen i blanketten hålls kort. Inga journaler eller diagnoser skrivs in i Underlaget. Intyget lämnas i slutet kuvert till Svenska Skolan Mallorca, som samordnar med Hermods. Skolverket bedömer om skälen är synnerliga. Appen tar inte ställning.",
    }),
  },
  {
    id: "enskild-firma",
    title: "Enskild firma",
    summary: "Stopp. Du är inte en juridisk person. Det finns ingen arbetsgivare som kan skriva under.",
    formName: "Går inte — byt spår",
    group: "dont",
    state: base({
      studentFirstName: "Kajsa",
      studentLastName: "Molin",
      studentDateOfBirth: "2010-10-08",
      year: "1",
      program: "ekonomi",
      guardian1: {
        firstName: "Per",
        lastName: "Molin",
        dateOfBirth: "1976-04-04",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Eva",
        lastName: "Molin",
        dateOfBirth: "1978-09-27",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2024-01",
      stayType: "indefinite",
      reason: "employment",
      employerForm: "sole_trader",
      isOwnerOrCeo: "yes",
      employerName: "Molin Konsult (enskild firma, exempel)",
      employerOrgNr: "760404-0000",
      employerAddress: "Carrer del Sol 3, Palma",
      employerCountry: "Spanien",
      jobTitle: "Konsult",
      employmentType: "permanent",
      workAbroadFrom: "2024-01",
      jobPoints: "Fakturerar egna uppdrag som fysisk person.",
      whyRaw:
        "Per fakturerar som enskild firma. Det ser ut som arbete utomlands, men det finns ingen juridisk person som arbetsgivare.",
      whyGenerated:
        "Det här spåret stannar. Enskild firma är inte en juridisk person. Skolverket godkänner inte Intyg om tjänstgöring när arbetsgivaren är du själv som fysisk person. Ingen kan skriva under del 2 åt dig. Byt bolagsform eller annan anledning — försök inte skriva under själv.",
      whyApproved: false,
      canIndependentSign: "",
      letterGenerated: "",
    }),
  },
  {
    id: "egen-underskrift",
    title: "VD skriver under själv",
    summary: "Stopp. Även om du äger AB:t får du inte skriva under ditt eget intyg.",
    formName: "Går inte — be extern revisor",
    group: "dont",
    state: base({
      studentFirstName: "Nils",
      studentLastName: "Broberg",
      studentDateOfBirth: "2009-07-19",
      year: "2",
      program: "ekonomi",
      guardian1: {
        firstName: "Carina",
        lastName: "Broberg",
        dateOfBirth: "1974-11-05",
        citizenship: "swedish",
      },
      guardian2: {
        firstName: "Stefan",
        lastName: "Broberg",
        dateOfBirth: "1973-02-14",
        citizenship: "swedish",
      },
      abroadGuardian: "1",
      stayFrom: "2023-06",
      stayType: "indefinite",
      reason: "employment",
      employerForm: "swedish_ab",
      isOwnerOrCeo: "yes",
      category: "C",
      employerName: "Broberg Teknik AB (exempel)",
      employerOrgNr: "559000-0404",
      employerAddress: "Carrer de la Pau 8, Palma",
      employerCountry: "Spanien",
      jobTitle: "VD",
      employmentType: "permanent",
      workAbroadFrom: "2023-06",
      jobPoints:
        "1. Driver bolagets uppdrag mot spanska kunder\n2. Är ensam firmatecknare",
      whyRaw:
        "Carina är VD och vill skriva under del 2 själv. Det går inte, även om bolaget är ett AB.",
      whyGenerated:
        "Bolaget är ett svenskt AB, vilket är rätt form. Felet är underskriften. Vårdnadshavaren får inte underteckna sitt eget Intyg om tjänstgöring, även som VD eller ägare. Be en extern revisor eller annan oberoende person med insyn i verksamheten. Er underskrift intygar inte att statsbidrag ska beviljas — och den får inte vara er egen.",
      whyApproved: false,
      canIndependentSign: "self",
      signerName: "Carina Broberg",
      signerTitle: "VD",
      signerType: "hr",
      letterGenerated: "",
    }),
  },
];

export function personaById(id: string | null | undefined): Persona | undefined {
  if (!id) return undefined;
  return PERSONAS.find((persona) => persona.id === id);
}
